_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
                - 82
            "2":
                - 1
                - 5
                - 37
                - 38
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
                - 82
            "3":
                - 13
                - 23
                - 24
                - 55
                - 61
            "4": 3.10.13
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
